services:
  server:
    image: node:22-alpine
    working_dir: /eve-incursions/packages/server
    restart: unless-stopped
    networks:
      - caddy
      - internal
    volumes:
      - ./:/eve-incursions
    environment:
      - DB_FILE=/eve-incursions/tmp/app.db

  scheduler:
    image: node:22-alpine
    working_dir: /eve-incursions/packages/server
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./:/eve-incursions
    environment:
      - DB_FILE=/eve-incursions/tmp/app.db

  ws:
    image: node:22-alpine
    working_dir: /eve-incursions/packages/ws
    restart: unless-stopped
    networks:
      - internal
      - caddy
    volumes:
      - ./:/eve-incursions

  frontend:
    image: node:22-alpine
    working_dir: /eve-incursions/packages/frontend
    restart: unless-stopped
    networks:
      - caddy
      - internal
    volumes:
      - ./:/eve-incursions

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - internal

networks:
  caddy:
    name: caddy
  internal:
