
services:
  init:
    image: node:22-alpine
    working_dir: /eve-incursions
    volumes:
      - ./:/eve-incursions
    command: npm i

  server:
    command: sh -c "npm start"
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
    - 4001:4001
    labels:
      caddy: localhost
      caddy.reverse_proxy: /api* {{upstreams 4001}}
      caddy.@cachedFiles.path: "*.jpg *.jpeg *.png *.gif *.ico *.svg"
      caddy.header: '@cachedFiles Cache-Control "public, max-age=604800, must-revalidate"'

  ws:
    command: sh -c "npm start"
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - 4003:4003
    labels:
      caddy: localhost
      caddy.reverse_proxy: /ws {{upstreams 4003}}

  frontend:
    command: sh -c "npm run dev"
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
    - 4002:3000
    labels:
      caddy: localhost
      caddy.reverse_proxy: /* {{upstreams 3000}}
      caddy.@cachedFiles.path: "*.jpg *.jpeg *.png *.gif *.ico *.svg"
      caddy.header: '@cachedFiles Cache-Control "public, max-age=604800, must-revalidate"'
