version: "3.7"

services:
  server:
    command: sh -c "npm i && npm start"
    ports:
    - 4001:4001

  frontend:
    command: sh -c "npm i && npm run dev"
    ports:
    - 4002:3000

  caddy:
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile

