version: "3.7"

services:
  server:
    command: sh -c "npm i && npm run prod"
    restart: unless-stopped

  frontend:
    command: sh -c "npm i && npm run build && npm start"
    restart: unless-stopped

  mysql:
    restart: unless-stopped

  caddy:
    restart: unless-stopped
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
